# -*- coding: utf-8 -*-
"""multi_agent_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CN3kZ9WzaX8cMYC8NtsYypaoEsGrpLH
"""

import os

# Folder structure
folders = [
    'project',
    'project/agents',
    'project/tools',
    'project/memory',
    'project/core'
]

# Create folders
for f in folders:
    os.makedirs(f, exist_ok=True)

# Add __init__.py to make them packages
for f in folders:
    if f != 'project': # Don't create __init__.py directly in the root 'project' if it's not meant to be a package itself
        init_file = os.path.join(f, '__init__.py')
        with open(init_file, 'w') as f_init:
            pass # Create an empty __init__.py file

print("Directories and __init__.py files created.")

# File templates
files = {
    'project/memory/session_memory.py': '''import json

class SessionMemory:
    def __init__(self, storage_file: str = None):
        self.store = {}
        self.storage_file = storage_file

    def get(self, session_id: str, default=None):
        return self.store.get(session_id, default)

    def set(self, session_id: str, value):
        self.store[session_id] = value

    def append_message(self, session_id: str, role: str, text: str):
        convo = self.store.setdefault(session_id, {'messages': []})
        convo['messages'].append({'role': role, 'text': text})

    def summarize_and_save(self, session_id: str, summary: str):
        self.store.setdefault(session_id, {})['summary'] = summary
        if self.storage_file:
            with open(self.storage_file, 'w') as f:
                json.dump(self.store, f)
''',

    'project/tools/sentiment.py': '''from typing import Dict, Any

class SentimentAnalyzer:
    def analyze(self, text: str) -> Dict[str, Any]:
        neg_words = ['sad', 'depressed', 'hopeless', 'anxious', 'angry']
        score = sum(1 for w in neg_words if w in text.lower()) / max(1, len(neg_words))
        return {'negative': score}
''',

    'project/tools/crisis.py': '''import re
from typing import Tuple, List

class CrisisDetector:
    def detect(self, text: str) -> Tuple[float, List[str]]:
        lowered = text.lower()
        flags = []
        score = 0.0
        if re.search(r'suicid|kill myself|end my life|want to die', lowered):
            flags.append('suicidal_ideation')
            score = 0.95
        return score, flags
''',

    'project/tools/safety.py': '''from typing import Tuple, List

class SafetyFilter:
    def check(self, text: str) -> Tuple[bool, List[str]]:
        issues = []
        if 'prescribe' in text.lower() or 'medication' in text.lower():
            issues.append('medical_claim')
        return (len(issues) > 0, issues)
''',

    'project/tools/exercise.py': '''class ExerciseGenerator:
    def generate(self, kind: str):
        if kind == 'breathing':
            return {'text': 'Try 4-4-4 breathing: inhale 4s, hold 4s, exhale 4s for 5 cycles', 'duration_s': 60}
        return {'text': 'Try grounding: 5-4-3-2-1', 'duration_s': 60}
''',

    'project/tools/resources.py': '''class ResourceDB:
    def __init__(self):
        self.data = {
            'global_hotline': '+1-800-123-4567',
            'advice': 'If you are in immediate danger call your local emergency services.'
        }

    def get_emergency_info(self):
        return {'hotline': self.data['global_hotline'], 'advice': self.data['advice']}
''',

    'project/tools/summarizer.py': '''class Summarizer:
    def summarize(self, text: str):
        short = text if len(text) < 200 else text[:197] + '...'
        return {'summary': short}
''',

    'project/agents/planner.py': '''import uuid
from project.memory.session_memory import SessionMemory
from project.tools.sentiment import SentimentAnalyzer
from project.tools.crisis import CrisisDetector

class Planner:
    def __init__(self, memory: SessionMemory = None):
        self.memory = memory or SessionMemory()
        self.sentiment = SentimentAnalyzer()
        self.crisis = CrisisDetector()

    def interpret(self, user_message: str, session_id: str):
        sentiment = self.sentiment.analyze(user_message)
        crisis_score, flags = self.crisis.detect(user_message)
        intent = self._classify_intent(user_message, sentiment, flags)
        tasks = self._build_tasks(intent, crisis_score)
        plan = {
            'plan_id': f'plan-{session_id}',
            'intent': intent,
            'crisis_score': crisis_score,
            'tasks': tasks,
            'metadata': {'sentiment': sentiment}
        }
        return self._make_plan_message('planner', 'worker', session_id, plan)

    def _classify_intent(self, text, sentiment, flags):
        if 'suicid' in text.lower() or 'kill myself' in text.lower() or 'hurt myself' in text.lower():
            return 'crisis'
        if sentiment.get('negative', 0) > 0.6:
            return 'support_request'
        return 'general_support'

    def _build_tasks(self, intent, crisis_score):
        tasks = [{'task_id': 't1', 'task_type': 'generate_reply'}]
        if intent in ['support_request', 'crisis']:
            tasks.append({'task_id': 't2', 'task_type': 'suggest_exercise'})
            tasks.append({'task_id': 't3', 'task_type': 'summarize_session'})
        if crisis_score >= 0.7:
            tasks.insert(0, {'task_id': 't0', 'task_type': 'escalate'})
        return tasks

    def _make_plan_message(self, from_agent, to_agent, session_id, plan):
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': from_agent,
            'to_agent': to_agent,
            'session_id': session_id,
            'payload_type': 'plan',
            'payload': plan,
            'audit_trail': [{'agent': from_agent}]
        }
''',

    'project/agents/worker.py': '''import uuid
from project.tools.safety import SafetyFilter
from project.tools.exercise import ExerciseGenerator
from project.tools.resources import ResourceDB
from project.tools.summarizer import Summarizer

class Worker:
    def __init__(self, memory=None):
        self.memory = memory
        self.safety = SafetyFilter()
        self.exercise = ExerciseGenerator()
        self.resources = ResourceDB()
        self.summarizer = Summarizer()

    def execute(self, task, user_message, session_id):
        task_type = task.get('task_type')
        if task_type == 'generate_reply':
            reply = {'text': "I hear you. Thanks for sharing - it sounds like you're experiencing something difficult. Would you like a short grounding exercise or resources?", 'style': 'empathetic'}
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], reply, ['generate_reply'])
        if task_type == 'suggest_exercise':
            ex = self.exercise.generate('breathing')
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], ex, ['exercise_generator'])
        if task_type == 'summarize_session':
            summ = self.summarizer.summarize(user_message)
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], summ, ['summarizer'])
        if task_type == 'escalate':
            info = self.resources.get_emergency_info()
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], info, ['resource_db'])
        return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], {'error': 'unknown task'}, [])

    def _make_task_result(self, from_agent, to_agent, session_id, task_id, result, tools_used):
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': from_agent,
            'to_agent': to_agent,
            'session_id': session_id,
            'payload_type': 'task_result',
            'payload': {'task_id': task_id, 'result': result, 'tools_used': tools_used},
            'audit_trail': [{'agent': from_agent}]
        }
''',

    'project/agents/evaluator.py': '''import uuid
from project.tools.safety import SafetyFilter

class Evaluator:
    def __init__(self): # Removed memory=None as it's not used internally and can be confusing
        self.safety = SafetyFilter()

    def evaluate(self, task_result, user_message, session_id):
        result = task_result['payload'].get('result')
        approved = True
        reasons = []
        if isinstance(result, dict) and 'text' in result:
            unsafe, issues = self.safety.check(result['text'])
            if unsafe:
                approved = False
                reasons.extend(issues)
        payload = {
            'task_id': task_result['payload']['task_id'],
            'approved': approved,
            'reasons': reasons,
            'revised_result': (result if approved else {'text': 'I am sorry, I cannot provide that.'})
        }
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': 'evaluator',
            'to_agent': 'main',
            'session_id': session_id,
            'payload_type': 'evaluation',
            'payload': payload,
            'audit_trail': [{'agent': 'evaluator'}]
        }
''',

    'project/core/main_agent.py': '''import time
from project.memory.session_memory import SessionMemory
from project.agents.planner import Planner
from project.agents.worker import Worker
from project.agents.evaluator import Evaluator

def log_event(event_type, payload):
    print({'ts': time.time(), 'type': event_type, 'payload': payload})

class MainAgent:
    def __init__(self):
        self.memory = SessionMemory()
        self.planner = Planner(self.memory)
        self.worker = Worker(self.memory)
        self.evaluator = Evaluator(self.memory)

    def handle_message(self, user_input, session_id='default'):
        log_event('request.received', {'session_id': session_id, 'text': user_input})
        plan_msg = self.planner.interpret(user_input, session_id)
        log_event('plan.generated', plan_msg)
        final_parts = []
        for task in plan_msg['payload']['tasks']:
            task_msg = self.worker.execute(task, user_input, session_id)
            log_event('task.executed', task_msg)
            eval_msg = self.evaluator.evaluate(task_msg, user_input, session_id)
            log_event('task.evaluated', eval_msg)
            final_parts.append(eval_msg['payload']['revised_result'])
        response_texts = [p.get('text') for p in final_parts if isinstance(p, dict)]
        response = "\\\\n\\\\n".join(response_texts) or "I'm here to listen."
        self.memory.append_message(session_id, 'assistant', response)
        return {'response': response, 'plan': plan_msg}

def run_agent("I feel very sad today."):
    agent = MainAgent()
    result = agent.handle_message(user_input)
    return result['response']
'''
}

# Write files
for path, content in files.items():
    with open(path, 'w') as f:
        f.write(content)

print("All files created successfully.")

import importlib
from project.core import main_agent
from project.memory import session_memory
from project.agents import planner
from project.agents import worker
from project.agents import evaluator
from project.tools import sentiment, crisis, safety, exercise, resources, summarizer

# Explicitly reload modules to ensure the latest definitions are used
importlib.reload(session_memory)
importlib.reload(sentiment)
importlib.reload(crisis)
importlib.reload(safety)
importlib.reload(exercise)
importlib.reload(resources)
importlib.reload(summarizer)
importlib.reload(planner)
importlib.reload(worker)
importlib.reload(evaluator)
importlib.reload(main_agent)


user_message = "I feel really sad and alone. I don't know what to do anymore."
response = main_agent.run_agent(user_message)
print(f"Agent Response: {response}")

# Install Mermaid support in Colab (if not already)
!pip install -q ipython

from IPython.display import display, Markdown

# Your Mermaid diagram code as a string
mermaid_code = """
graph TD
    U[User] -->|1. user_input| MA(MainAgent);
    MA -- "2. Calls Planner.interpret" --> P(Planner);
    P -- "3. Returns plan_msg" --> MA;

    subgraph Planner Internal Tools
        P -->|Sentiment Analysis| SA(SentimentAnalyzer);
        P -->|Crisis Detection| CD(CrisisDetector);
    end

    MA -- "4. Calls Worker.execute (for each task)" --> W(Worker);

    subgraph Worker Internal Tools
        W -->|Safety Check| SF_W(SafetyFilter);
        W -->|Generate Exercise| EG(ExerciseGenerator);
        W -->|Get Resources| RD(ResourceDB);
        W -->|Summarize| SU(Summarizer);
    end

    W -- "5. Returns task_result" --> MA;

    MA -- "6. Calls Evaluator.evaluate" --> E(Evaluator);

    subgraph Evaluator Internal Tools
        E -->|Safety Check| SF_E(SafetyFilter);
    end

    E -- "7. Returns evaluation" --> MA;

    MA -- "8. Stores conversation" --> SM[SessionMemory];
    MA -- "9. Logs events" --> O[Observability];

    MA -->|10. Sends response| U;

    MA -.-> P;
    P -.-> MA;
    MA -.-> W;
    W -.-> E;
    E -.-> MA;

    classDef agent fill:#ADD8E6,stroke:#00008B,stroke-width:2px;
    class MA,P,W,E agent;

    classDef tool fill:#E0FFFF,stroke:#4682B4,stroke-width:1px;
    class SA,CD,SF_W,EG,RD,SU,SF_E tool;

    classDef memory fill:#FFFACD,stroke:#DAA520,stroke-width:1px;
    class SM memory;

    classDef observability fill:#F0F8FF,stroke:#708090,stroke-width:1px;
    class O observability;

    classDef user fill:#FFC0CB,stroke:#C71585,stroke-width:2px;
    class U user;
"""

# Render Mermaid diagram
display(Markdown(f"```mermaid\n{mermaid_code}\n```"))

"""# Task
Read the content of "project/core/main_agent.py" and print it to identify any potential syntax issues.

## Recreate Project Files

### Subtask:
Re-run the initial cell that creates all the project folders and writes the file templates, including the potentially problematic `main_agent.py`.

**Reasoning**:
The subtask requires re-running the initial cell that creates project folders and file templates. I will execute the content of the cell with ID `4Ej9AH-rj3y0`.
"""

import os

# Folder structure
folders = [
    'project',
    'project/agents',
    'project/tools',
    'project/memory',
    'project/core'
]

# Create folders
for f in folders:
    os.makedirs(f, exist_ok=True)

# Add __init__.py to make them packages
for f in folders:
    if f != 'project': # Don't create __init__.py directly in the root 'project' if it's not meant to be a package itself
        init_file = os.path.join(f, '__init__.py')
        with open(init_file, 'w') as f_init:
            pass # Create an empty __init__.py file

print("Directories and __init__.py files created.")

# File templates
files = {
    'project/memory/session_memory.py': """import json

class SessionMemory:
    def __init__(self, storage_file: str = None):
        self.store = {}
        self.storage_file = storage_file

    def get(self, session_id: str, default=None):
        return self.store.get(session_id, default)

    def set(self, session_id: str, value):
        self.store[session_id] = value

    def append_message(self, session_id: str, role: str, text: str):
        convo = self.store.setdefault(session_id, {'messages': []})
        convo['messages'].append({'role': role, 'text': text})

    def summarize_and_save(self, session_id: str, summary: str):
        self.store.setdefault(session_id, {})['summary'] = summary
        if self.storage_file:
            with open(self.storage_file, 'w') as f:
                json.dump(self.store, f)
""",

    'project/tools/sentiment.py': """from typing import Dict, Any

class SentimentAnalyzer:
    def analyze(self, text: str) -> Dict[str, Any]:
        neg_words = ['sad', 'depressed', 'hopeless', 'anxious', 'angry']
        score = sum(1 for w in neg_words if w in text.lower()) / max(1, len(neg_words))
        return {'negative': score}
""",

    'project/tools/crisis.py': """import re
from typing import Tuple, List

class CrisisDetector:
    def detect(self, text: str) -> Tuple[float, List[str]]:
        lowered = text.lower()
        flags = []
        score = 0.0
        if re.search(r'suicid|kill myself|end my life|want to die', lowered):
            flags.append('suicidal_ideation')
            score = 0.95
        return score, flags
""",

    'project/tools/safety.py': """from typing import Tuple, List

class SafetyFilter:
    def check(self, text: str) -> Tuple[bool, List[str]]:
        issues = []
        if 'prescribe' in text.lower() or 'medication' in text.lower():
            issues.append('medical_claim')
        return (len(issues) > 0, issues)
""",

    'project/tools/exercise.py': """class ExerciseGenerator:
    def generate(self, kind: str):
        if kind == 'breathing':
            return {'text': 'Try 4-4-4 breathing: inhale 4s, hold 4s, exhale 4s for 5 cycles', 'duration_s': 60}
        return {'text': 'Try grounding: 5-4-3-2-1', 'duration_s': 60}
""",

    'project/tools/resources.py': """class ResourceDB:
    def __init__(self):
        self.data = {
            'global_hotline': '+1-800-123-4567',
            'advice': 'If you are in immediate danger call your local emergency services.'
        }

    def get_emergency_info(self):
        return {'hotline': self.data['global_hotline'], 'advice': self.data['advice']}
""",

    'project/tools/summarizer.py': """class Summarizer:
    def summarize(self, text: str):
        short = text if len(text) < 200 else text[:197] + '...'
        return {'summary': short}
""",

    'project/agents/planner.py': """import uuid
from project.memory.session_memory import SessionMemory
from project.tools.sentiment import SentimentAnalyzer
from project.tools.crisis import CrisisDetector

class Planner:
    def __init__(self, memory: SessionMemory = None):
        self.memory = memory or SessionMemory()
        self.sentiment = SentimentAnalyzer()
        self.crisis = CrisisDetector()

    def interpret(self, user_message: str, session_id: str):
        sentiment = self.sentiment.analyze(user_message)
        crisis_score, flags = self.crisis.detect(user_message)
        intent = self._classify_intent(user_message, sentiment, flags)
        tasks = self._build_tasks(intent, crisis_score)
        plan = {
            'plan_id': f'plan-{session_id}',
            'intent': intent,
            'crisis_score': crisis_score,
            'tasks': tasks,
            'metadata': {'sentiment': sentiment}
        }
        return self._make_plan_message('planner', 'worker', session_id, plan)

    def _classify_intent(self, text, sentiment, flags):
        if 'suicid' in text.lower() or 'kill myself' in text.lower() or 'hurt myself' in text.lower():
            return 'crisis'
        if sentiment.get('negative', 0) > 0.6:
            return 'support_request'
        return 'general_support'

    def _build_tasks(self, intent, crisis_score):
        tasks = [{'task_id': 't1', 'task_type': 'generate_reply'}]
        if intent in ['support_request', 'crisis']:
            tasks.append({'task_id': 't2', 'task_type': 'suggest_exercise'})
            tasks.append({'task_id': 't3', 'task_type': 'summarize_session'})
        if crisis_score >= 0.7:
            tasks.insert(0, {'task_id': 't0', 'task_type': 'escalate'})
        return tasks

    def _make_plan_message(self, from_agent, to_agent, session_id, plan):
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': from_agent,
            'to_agent': to_agent,
            'session_id': session_id,
            'payload_type': 'plan',
            'payload': plan,
            'audit_trail': [{'agent': from_agent}]
        }
""",

    'project/agents/worker.py': """import uuid
from project.tools.safety import SafetyFilter
from project.tools.exercise import ExerciseGenerator
from project.tools.resources import ResourceDB
from project.tools.summarizer import Summarizer

class Worker:
    def __init__(self, memory=None):
        self.memory = memory
        self.safety = SafetyFilter()
        self.exercise = ExerciseGenerator()
        self.resources = ResourceDB()
        self.summarizer = Summarizer()

    def execute(self, task, user_message, session_id):
        task_type = task.get('task_type')
        if task_type == 'generate_reply':
            reply = {'text': "I hear you. Thanks for sharing - it sounds like you're experiencing something difficult. Would you like a short grounding exercise or resources?", 'style': 'empathetic'}
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], reply, ['generate_reply'])
        if task_type == 'suggest_exercise':
            ex = self.exercise.generate('breathing')
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], ex, ['exercise_generator'])
        if task_type == 'summarize_session':
            summ = self.summarizer.summarize(user_message)
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], summ, ['summarizer'])
        if task_type == 'escalate':
            info = self.resources.get_emergency_info()
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], info, ['resource_db'])
        return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], {'error': 'unknown task'}, [])

    def _make_task_result(self, from_agent, to_agent, session_id, task_id, result, tools_used):
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': from_agent,
            'to_agent': to_agent,
            'session_id': session_id,
            'payload_type': 'task_result',
            'payload': {'task_id': task_id, 'result': result, 'tools_used': tools_used},
            'audit_trail': [{'agent': from_agent}]
        }
""",

    'project/agents/evaluator.py': """import uuid
from project.tools.safety import SafetyFilter

class Evaluator:
    def __init__(self):
        self.safety = SafetyFilter()

    def evaluate(self, task_result, user_message, session_id):
        result = task_result['payload'].get('result')
        approved = True
        reasons = []
        if isinstance(result, dict) and 'text' in result:
            unsafe, issues = self.safety.check(result['text'])
            if unsafe:
                approved = False
                reasons.extend(issues)
        payload = {
            'task_id': task_result['payload']['task_id'],
            'approved': approved,
            'reasons': reasons,
            'revised_result': (result if approved else {'text': 'I am sorry, I cannot provide that.'})
        }
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': 'evaluator',
            'to_agent': 'main',
            'session_id': session_id,
            'payload_type': 'evaluation',
            'payload': payload,
            'audit_trail': [{'agent': 'evaluator'}]
        }
""",

    'project/core/main_agent.py': """import time
from project.memory.session_memory import SessionMemory
from project.agents.planner import Planner
from project.agents.worker import Worker
from project.agents.evaluator import Evaluator

def log_event(event_type, payload):
    print({'ts': time.time(), 'type': event_type, 'payload': payload})

class MainAgent:
    def __init__(self):
        self.memory = SessionMemory()
        self.planner = Planner(self.memory)
        self.worker = Worker(self.memory)
        self.evaluator = Evaluator() # Corrected: Removed self.memory argument

    def handle_message(self, user_input, session_id='default'):
        log_event('request.received', {'session_id': session_id, 'text': user_input})
        plan_msg = self.planner.interpret(user_input, session_id)
        log_event('plan.generated', plan_msg)
        final_parts = []
        for task in plan_msg['payload']['tasks']:
            task_msg = self.worker.execute(task, user_input, session_id)
            log_event('task.executed', task_msg)
            eval_msg = self.evaluator.evaluate(task_msg, user_input, session_id)
            log_event('task.evaluated', eval_msg)
            final_parts.append(eval_msg['payload']['revised_result'])
        response_texts = [p.get('text') for p in final_parts if isinstance(p, dict)]
        response = "\\n\\n".join(response_texts) or "I'm here to listen."
        self.memory.append_message(session_id, 'assistant', response)
        return {'response': response, 'plan': plan_msg}

def run_agent(user_input):
    agent = MainAgent()
    result = agent.handle_message(user_input)
    return result['response']
"""
}

# Write files
for path, content in files.items():
    with open(path, 'w') as f:
        f.write(content)

print("All files created successfully.")

"""**Reasoning**:
To identify any potential syntax issues, I will read the content of the specified file, 'project/core/main_agent.py', and print it to the console.


"""

with open('project/core/main_agent.py', 'r') as f:
    main_agent_content = f.read()
print(main_agent_content)

"""## Final Task

### Subtask:
Analyze the printed `main_agent.py` content to identify any discrepancies or hidden characters that might be causing the `SyntaxError`, and then determine the next steps.

## Summary:

### Q&A
*   **Were any discrepancies or hidden characters identified in `main_agent.py` that might be causing a `SyntaxError`?**
    No obvious syntax errors or hidden characters were identified in the printed content of `project/core/main_agent.py`.

### Data Analysis Key Findings
*   The project directory structure and all associated Python files, including `project/core/main_agent.py`, were successfully created as confirmed by the output "Directories and \_\_init\_\_.py files created.\nAll files created successfully."
*   The content of `project/core/main_agent.py` was successfully read and printed without revealing any immediate or obvious `SyntaxError` within its static code.

### Insights or Next Steps
*   Since the static content of `main_agent.py` appears correct, the previously reported `SyntaxError` is likely to arise during the execution or import of the module, rather than from a visible issue in the file's text.
*   The next step should involve attempting to import `main_agent.py` or run a function from it to reproduce the `SyntaxError` and obtain a more specific traceback for debugging.

# Task
Correct the file template escaping in `project/core/main_agent.py` within the `files` dictionary in cell `50368211` by changing `"\n\n"` to `"\\n\\n"` in the `response = ...` line, then re-run cell `50368211` to update the file, and finally re-run cell `361f352f` to execute the agent.

## Correct File Template Escaping

### Subtask:
Modify the file creation cell (50368211) to double-escape the newline characters within the `main_agent.py` content string.

**Reasoning**:
To fix the `SyntaxError` caused by unescaped newline characters in the `main_agent.py` template string, I will modify the `code_block` of cell `50368211` to explicitly double-escape the newline characters within the `response = ` line. This will ensure the Python string is correctly formed when written to the file.
"""

import os

# Folder structure
holders = [
    'project',
    'project/agents',
    'project/tools',
    'project/memory',
    'project/core'
]

# Create folders
for f in folders:
    os.makedirs(f, exist_ok=True)

# Add __init__.py to make them packages
for f in folders:
    if f != 'project': # Don't create __init__.py directly in the root 'project' if it's not meant to be a package itself
        init_file = os.path.join(f, '__init__.py')
        with open(init_file, 'w') as f_init:
            pass # Create an empty __init__.py file

print("Directories and __init__.py files created.")

# File templates
files = {
    'project/memory/session_memory.py': """import json

class SessionMemory:
    def __init__(self, storage_file: str = None):
        self.store = {}
        self.storage_file = storage_file

    def get(self, session_id: str, default=None):
        return self.store.get(session_id, default)

    def set(self, session_id: str, value):
        self.store[session_id] = value

    def append_message(self, session_id: str, role: str, text: str):
        convo = self.store.setdefault(session_id, {'messages': []})
        convo['messages'].append({'role': role, 'text': text})

    def summarize_and_save(self, session_id: str, summary: str):
        self.store.setdefault(session_id, {})['summary'] = summary
        if self.storage_file:
            with open(self.storage_file, 'w') as f:
                json.dump(self.store, f)
""",

    'project/tools/sentiment.py': """from typing import Dict, Any

class SentimentAnalyzer:
    def analyze(self, text: str) -> Dict[str, Any]:
        neg_words = ['sad', 'depressed', 'hopeless', 'anxious', 'angry']
        score = sum(1 for w in neg_words if w in text.lower()) / max(1, len(neg_words))
        return {'negative': score}
""",

    'project/tools/crisis.py': """import re
from typing import Tuple, List

class CrisisDetector:
    def detect(self, text: str) -> Tuple[float, List[str]]:
        lowered = text.lower()
        flags = []
        score = 0.0
        if re.search(r'suicid|kill myself|end my life|want to die', lowered):
            flags.append('suicidal_ideation')
            score = 0.95
        return score, flags
""",

    'project/tools/safety.py': """from typing import Tuple, List

class SafetyFilter:
    def check(self, text: str) -> Tuple[bool, List[str]]:
        issues = []
        if 'prescribe' in text.lower() or 'medication' in text.lower():
            issues.append('medical_claim')
        return (len(issues) > 0, issues)
""",

    'project/tools/exercise.py': """class ExerciseGenerator:
    def generate(self, kind: str):
        if kind == 'breathing':
            return {'text': 'Try 4-4-4 breathing: inhale 4s, hold 4s, exhale 4s for 5 cycles', 'duration_s': 60}
        return {'text': 'Try grounding: 5-4-3-2-1', 'duration_s': 60}
""",

    'project/tools/resources.py': """class ResourceDB:
    def __init__(self):
        self.data = {
            'global_hotline': '+1-800-123-4567',
            'advice': 'If you are in immediate danger call your local emergency services.'
        }

    def get_emergency_info(self):
        return {'hotline': self.data['global_hotline'], 'advice': self.data['advice']}
""",

    'project/tools/summarizer.py': """class Summarizer:
    def summarize(self, text: str):
        short = text if len(text) < 200 else text[:197] + '...'
        return {'summary': short}
""",

    'project/agents/planner.py': """import uuid
from project.memory.session_memory import SessionMemory
from project.tools.sentiment import SentimentAnalyzer
from project.tools.crisis import CrisisDetector

class Planner:
    def __init__(self, memory: SessionMemory = None):
        self.memory = memory or SessionMemory()
        self.sentiment = SentimentAnalyzer()
        self.crisis = CrisisDetector()

    def interpret(self, user_message: str, session_id: str):
        sentiment = self.sentiment.analyze(user_message)
        crisis_score, flags = self.crisis.detect(user_message)
        intent = self._classify_intent(user_message, sentiment, flags)
        tasks = self._build_tasks(intent, crisis_score)
        plan = {
            'plan_id': f'plan-{session_id}',
            'intent': intent,
            'crisis_score': crisis_score,
            'tasks': tasks,
            'metadata': {'sentiment': sentiment}
        }
        return self._make_plan_message('planner', 'worker', session_id, plan)

    def _classify_intent(self, text, sentiment, flags):
        if 'suicid' in text.lower() or 'kill myself' in text.lower() or 'hurt myself' in text.lower():
            return 'crisis'
        if sentiment.get('negative', 0) > 0.6:
            return 'support_request'
        return 'general_support'

    def _build_tasks(self, intent, crisis_score):
        tasks = [{'task_id': 't1', 'task_type': 'generate_reply'}]
        if intent in ['support_request', 'crisis']:
            tasks.append({'task_id': 't2', 'task_type': 'suggest_exercise'})
            tasks.append({'task_id': 't3', 'task_type': 'summarize_session'})
        if crisis_score >= 0.7:
            tasks.insert(0, {'task_id': 't0', 'task_type': 'escalate'})
        return tasks

    def _make_plan_message(self, from_agent, to_agent, session_id, plan):
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': from_agent,
            'to_agent': to_agent,
            'session_id': session_id,
            'payload_type': 'plan',
            'payload': plan,
            'audit_trail': [{'agent': from_agent}]
        }
""",

    'project/agents/worker.py': """import uuid
from project.tools.safety import SafetyFilter
from project.tools.exercise import ExerciseGenerator
from project.tools.resources import ResourceDB
from project.tools.summarizer import Summarizer

class Worker:
    def __init__(self, memory=None):
        self.memory = memory
        self.safety = SafetyFilter()
        self.exercise = ExerciseGenerator()
        self.resources = ResourceDB()
        self.summarizer = Summarizer()

    def execute(self, task, user_message, session_id):
        task_type = task.get('task_type')
        if task_type == 'generate_reply':
            reply = {'text': "I hear you. Thanks for sharing - it sounds like you're experiencing something difficult. Would you like a short grounding exercise or resources?", 'style': 'empathetic'}
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], reply, ['generate_reply'])
        if task_type == 'suggest_exercise':
            ex = self.exercise.generate('breathing')
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], ex, ['exercise_generator'])
        if task_type == 'summarize_session':
            summ = self.summarizer.summarize(user_message)
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], summ, ['summarizer'])
        if task_type == 'escalate':
            info = self.resources.get_emergency_info()
            return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], info, ['resource_db'])
        return self._make_task_result('worker', 'evaluator', session_id, task['task_id'], {'error': 'unknown task'}, [])

    def _make_task_result(self, from_agent, to_agent, session_id, task_id, result, tools_used):
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': from_agent,
            'to_agent': to_agent,
            'session_id': session_id,
            'payload_type': 'task_result',
            'payload': {'task_id': task_id, 'result': result, 'tools_used': tools_used},
            'audit_trail': [{'agent': from_agent}]
        }
""",

    'project/agents/evaluator.py': """import uuid
from project.tools.safety import SafetyFilter

class Evaluator:
    def __init__(self, memory=None):
        self.memory = memory
        self.safety = SafetyFilter()

    def evaluate(self, task_result, user_message, session_id):
        result = task_result['payload'].get('result')
        approved = True
        reasons = []
        if isinstance(result, dict) and 'text' in result:
            unsafe, issues = self.safety.check(result['text'])
            if unsafe:
                approved = False
                reasons.extend(issues)
        payload = {
            'task_id': task_result['payload']['task_id'],
            'approved': approved,
            'reasons': reasons,
            'revised_result': (result if approved else {'text': 'I am sorry, I cannot provide that.'})
        }
        return {
            'message_id': str(uuid.uuid4()),
            'from_agent': 'evaluator',
            'to_agent': 'main',
            'session_id': session_id,
            'payload_type': 'evaluation',
            'payload': payload,
            'audit_trail': [{'agent': 'evaluator'}]
        }
""",

    'project/core/main_agent.py': """import time
from project.memory.session_memory import SessionMemory
from project.agents.planner import Planner
from project.agents.worker import Worker
from project.agents.evaluator import Evaluator

def log_event(event_type, payload):
    print({'ts': time.time(), 'type': event_type, 'payload': payload})

class MainAgent:
    def __init__(self):
        self.memory = SessionMemory()
        self.planner = Planner(self.memory)
        self.worker = Worker(self.memory)
        self.evaluator = Evaluator(self.memory)

    def handle_message(self, user_input, session_id='default'):
        log_event('request.received', {'session_id': session_id, 'text': user_input})
        plan_msg = self.planner.interpret(user_input, session_id)
        log_event('plan.generated', plan_msg)
        final_parts = []
        for task in plan_msg['payload']['tasks']:
            task_msg = self.worker.execute(task, user_input, session_id)
            log_event('task.executed', task_msg)
            eval_msg = self.evaluator.evaluate(task_msg, user_input, session_id)
            log_event('task.evaluated', eval_msg)
            final_parts.append(eval_msg['payload']['revised_result'])
        response_texts = [p.get('text') for p in final_parts if isinstance(p, dict)]
        response = "\\n\\n".join(response_texts) or "I'm here to listen."
        self.memory.append_message(session_id, 'assistant', response)
        return {'response': response, 'plan': plan_msg}

def run_agent(user_input):
    agent = MainAgent()
    result = agent.handle_message(user_input)
    return result['response']
"""
}

# Write files
for path, content in files.items():
    with open(path, 'w') as f:
        f.write(content)

print("All files created successfully.")

"""**Reasoning**:
The file `main_agent.py` has been updated with the corrected escape characters. To ensure the Python interpreter uses the latest version of the module, I need to explicitly reload `main_agent` and any other relevant modules before re-running the agent.


"""

import importlib
from project.core import main_agent
from project.memory import session_memory
from project.agents import planner
from project.agents import worker
from project.agents import evaluator
from project.tools import sentiment, crisis, safety, exercise, resources, summarizer

# Explicitly reload modules to ensure the latest definitions are used
importlib.reload(session_memory)
importlib.reload(sentiment)
importlib.reload(crisis)
importlib.reload(safety)
importlib.reload(exercise)
importlib.reload(resources)
importlib.reload(summarizer)
importlib.reload(planner)
importlib.reload(worker)
importlib.reload(evaluator)
importlib.reload(main_agent)


user_message = "I feel really sad and alone. I don't know what to do anymore."
response = main_agent.run_agent(user_message)
print(f"Agent Response: {response}")

"""## Summary:

### Data Analysis Key Findings
*   **Escaping Issue Resolved:** The core issue of incorrect newline escaping within the `project/core/main_agent.py` file template was successfully addressed by changing `"\n\n"` to `"\\n\\n"` in the `files` dictionary in cell `50368211`.
*   **Successful File Generation:** All necessary directories and Python files, including the corrected `main_agent.py`, were created successfully.
*   **Agent Execution Validation:** After reloading all relevant modules, the `MainAgent` executed without errors when processing the input "I feel really sad and alone. I don't know what to do anymore.".
*   **Coherent Agent Response:** The agent generated a relevant and empathetic response: "I hear you. Thanks for sharing - it sounds like you're experiencing something difficult. Would you like a short grounding exercise or resources?". The absence of `SyntaxError` confirms the fix was effective.

### Insights or Next Steps
*   **Insight:** Proper string escaping is crucial when defining multi-line string literals that represent code or text to be written to files, especially when dealing with backslashes or special characters that could be misinterpreted by the Python interpreter during string parsing.
*   **Next Steps:** Implement unit tests for the individual agents and integration tests for the `MainAgent`'s `handle_message` function to prevent similar syntax or runtime errors from reoccurring and ensure consistent behavior across different inputs.

"""